### ISSUE TITLE
Query Id (token expired)

### ISSUE THREAD

**Issue by FelipeDeFi** [OrrnobMahmud/MoonbixAuto#7]
Which one should be the correct?

![image](https://github.com/user-attachments/assets/f8eb9364-57f0-46e3-9f03-41dd11f004f9)

should I use it like 'query "something"' and that's it?

**Comment by Domenick90** [comment]
SAME!

**Comment by OrrnobMahmud** [comment]
![image](https://github.com/user-attachments/assets/290220f2-3c06-499d-bec5-13a7ab07d6f4)


update the bot and use python 3.10

**Comment by Domenick90** [comment]
For ru-section binance.com/RU/game/tg/moon-bix in Session Storage in tgWebAppData There is no query_id=*** in the string ,  string starting from user. Where else can you get the query_id ?
![image](https://github.com/user-attachments/assets/3290acc8-df8b-4b39-91e5-d63bb87197f9)

**Comment by alimurar** [comment]
It's already a query id, but some query ids start with user.
