### ISSUE TITLE
NO Query_id sting

### ISSUE THREAD

**Issue by Domenick90** [OrrnobMahmud/MoonbixAuto#8]
For ru-section binance.com/RU/game/tg/moon-bix in Session Storage in tgWebAppData There is no query_id=*** in the string , string starting from user. Where else can you get the query_id ?
![image](https://github.com/user-attachments/assets/e7c55a3e-ee0d-4857-946c-66d95b2d6541)

**Comment by huykhaduy** [comment]
Try this
![image](https://github.com/user-attachments/assets/41c23e8a-2d35-44ae-819d-da71b5e281ab)

**Comment by Domenick90** [comment]
Same, line without query_id, started from user=%....

**Comment by OrrnobMahmud** [comment]
both query and user are same.
