### ISSUE TITLE
Auto Play Game: Fail

### ISSUE THREAD

**Issue by miliardov** [OrrnobMahmud/MoonbixAuto#9]
![moonbix](https://github.com/user-attachments/assets/bc322539-42ae-402f-986f-a0616c3232cb)

The script was working yesterday. Then it stopped, Auto Play Game: Fail. Today also does not work.

**Comment by huykhaduy** [comment]
i don't know why but mine is fine, maybe you should update your token 
![image](https://github.com/user-attachments/assets/aa6ba1ec-25b6-4e1e-a713-a0583700095b)

**Comment by OrrnobMahmud** [comment]
did you update to the latest version?

**Comment by miliardov** [comment]
> Вы обновились до последней версии?

Yes, I just downloaded everything yesterday. it worked at first yesterday, then stopped after a couple hours, I didn't make any changes to the code. Today it's not working again.
